### ISSUE TITLE
Trouble building bootable USB

### ISSUE THREAD

**Issue by J0shuaT** [MilkyDeveloper/cb-linux#10]
I am having a lot of trouble creating the buildable usb. I’ve tried using a live linux USB, crouton on my chromebook, and Windows Subsystem for Linux on Windows 10. I ran into problems on all three. Is it possible to build it on Chromebook crostini? Or should I try again on WSL? Please help, as I would like to use Breath linux on my chromebook during an upcoming holiday road trip.

**Comment by jj1425** [comment]
I had a lot of trouble getting it set up too, but eventually got there - I wasn't able to get it working in WSL or Crouton after much troubleshooting, I guess there's just too many variables and overheads with the way they work - I could only get it set up in the end using a full Ubuntu 20.04 install on a different machine.

**Comment by MilkyDeveloper** [comment]
The *only* way to set it up is to use an Ubuntu live USB or install. I do not think Crouton works. I'll update the docs to reflect this.

**Comment by MilkyDeveloper** [comment]
Done!
