### ISSUE TITLE
Finding sound modules without /dev/mmcblk0p3 on Nami board

### ISSUE THREAD

**Issue by IvanFonarev** [MilkyDeveloper/cb-linux#11]
I'm try to install Ubuntu for friend chromebook (Dell Inspiron 14 2-in-1 Model 7486). I am facing a problem with sound setting. The chromebook does not have / dev / mmcblk0p3, however, the script requires it in order to copy modules and firmware from there. Where can I download the required files separately? What am I doing wrong?
_find /usr/share/alsa_

root@ubuntu:~# find /usr/share/alsa
/usr/share/alsa
/usr/share/alsa/cards
/usr/share/alsa/cards/Aureon51.conf
/usr/share/alsa/cards/ICH4.conf
/usr/share/alsa/cards/AU8820.conf
/usr/share/alsa/cards/NFORCE.conf
/usr/share/alsa/cards/FireWave.conf
/usr/share/alsa/cards/USB-Audio.conf
/usr/share/alsa/cards/YMF744.conf
/usr/share/alsa/cards/CS46xx.conf
/usr/share/alsa/cards/ICH.conf
/usr/share/alsa/cards/Maestro3.conf
/usr/share/alsa/cards/Loopback.conf
/usr/share/alsa/cards/VIA686A.conf
/usr/share/alsa/cards/SB-XFi.conf
/usr/share/alsa/cards/ATIIXP-SPDMA.conf
/usr/share/alsa/cards/PC-Speaker.conf
/usr/share/alsa/cards/CMI8788.conf
/usr/share/alsa/cards/ICE1724.conf
/usr/share/alsa/cards/ES1968.conf
/usr/share/alsa/cards/pistachio-card.conf
/usr/share/alsa/cards/PS3.conf
/usr/share/alsa/cards/CMI8738-MC8.conf
/usr/share/alsa/cards/ENS1370.conf
/usr/share/alsa/cards/RME9652.conf
/usr/share/alsa/cards/ICE1712.conf
/usr/share/alsa/cards/FWSpeakers.conf
/usr/share/alsa/cards/Aureon71.conf
/usr/share/alsa/cards/VXPocket440.conf
/usr/share/alsa/cards/HdmiLpeAudio.conf
/usr/share/alsa/cards/RME9636.conf
/usr/share/alsa/cards/PMac.conf
/usr/share/alsa/cards/VXPocket.conf
/usr/share/alsa/cards/AU8830.conf
/usr/share/alsa/cards/EMU10K1X.conf
/usr/share/alsa/cards/GUS.conf
/usr/share/alsa/cards/HDA-Intel.conf
/usr/share/alsa/cards/CMI8338.conf
/usr/share/alsa/cards/ENS1371.conf
/usr/share/alsa/cards/TRID4DWAVENX.conf
/usr/share/alsa/cards/ICH-MODEM.conf
/usr/share/alsa/cards/aliases.conf
/usr/share/alsa/cards/EMU10K1.conf
/usr/share/alsa/cards/AACI.conf
/usr/share/alsa/cards/Audigy2.conf
/usr/share/alsa/cards/CMI8338-SWIEC.conf
/usr/share/alsa/cards/Audigy.conf
/usr/share/alsa/cards/AU8810.conf
/usr/share/alsa/cards/VIA8233A.conf
/usr/share/alsa/cards/PMacToonie.conf
/usr/share/alsa/cards/VIA8233.conf
/usr/share/alsa/cards/CMI8738-MC6.conf
/usr/share/alsa/cards/VIA8237.conf
/usr/share/alsa/cards/ATIIXP-MODEM.conf
/usr/share/alsa/cards/VX222.conf
/usr/share/alsa/cards/ATIIXP.conf
/usr/share/alsa/cards/SI7018.conf
/usr/share/alsa/cards/CA0106.conf
/usr/share/alsa/cards/Echo_Echo3G.conf
/usr/share/alsa/cards/vc4-hdmi.conf
/usr/share/alsa/cards/FM801.conf
/usr/share/alsa/alsa.conf.d
/usr/share/alsa/alsa.conf.d/98-usb-stream.conf
/usr/share/alsa/alsa.conf.d/50-oss.conf
/usr/share/alsa/alsa.conf.d/50-arcam-av-ctl.conf
/usr/share/alsa/alsa.conf.d/50-pulseaudio.conf
/usr/share/alsa/alsa.conf.d/10-samplerate.conf
/usr/share/alsa/alsa.conf.d/60-vdownmix.conf
/usr/share/alsa/alsa.conf.d/10-speexrate.conf
/usr/share/alsa/alsa.conf.d/50-jack.conf
/usr/share/alsa/alsa.conf.d/60-upmix.conf
/usr/share/alsa/init
/usr/share/alsa/init/ca0106
/usr/share/alsa/init/ens1371
/usr/share/alsa/init/test
/usr/share/alsa/init/info
/usr/share/alsa/init/00main
/usr/share/alsa/init/help
/usr/share/alsa/init/hda
/usr/share/alsa/init/default
/usr/share/alsa/pcm
/usr/share/alsa/pcm/surround51.conf
/usr/share/alsa/pcm/surround41.conf
/usr/share/alsa/pcm/side.conf
/usr/share/alsa/pcm/surround40.conf
/usr/share/alsa/pcm/dpl.conf
/usr/share/alsa/pcm/iec958.conf
/usr/share/alsa/pcm/dsnoop.conf
/usr/share/alsa/pcm/dmix.conf
/usr/share/alsa/pcm/default.conf
/usr/share/alsa/pcm/modem.conf
/usr/share/alsa/pcm/front.conf
/usr/share/alsa/pcm/surround50.conf
/usr/share/alsa/pcm/surround71.conf
/usr/share/alsa/pcm/rear.conf
/usr/share/alsa/pcm/hdmi.conf
/usr/share/alsa/pcm/surround21.conf
/usr/share/alsa/pcm/center_lfe.conf
/usr/share/alsa/ucm
/usr/share/alsa/ucm/README.md
/usr/share/alsa/utils.sh
/usr/share/alsa/speaker-test
/usr/share/alsa/speaker-test/sample_map.csv
/usr/share/alsa/alsa.conf
/usr/share/alsa/topology
/usr/share/alsa/topology/bxtrt298
/usr/share/alsa/topology/bxtrt298/bxt_i2s.conf
/usr/share/alsa/topology/broadwell
/usr/share/alsa/topology/broadwell/broadwell.conf
/usr/share/alsa/topology/sklrt286
/usr/share/alsa/topology/sklrt286/skl_i2s.conf
/usr/share/alsa/ucm2
/usr/share/alsa/ucm2/codecs
/usr/share/alsa/ucm2/codecs/rt711-sdca
/usr/share/alsa/ucm2/codecs/rt711-sdca/init.conf
/usr/share/alsa/ucm2/codecs/rt711
/usr/share/alsa/ucm2/codecs/rt711/init.conf
/usr/share/alsa/ucm2/codecs/rt5640
/usr/share/alsa/ucm2/codecs/rt5640/IN1-InternalMic.conf
/usr/share/alsa/ucm2/codecs/rt5640/Speaker.conf
/usr/share/alsa/ucm2/codecs/rt5640/DigitalMics.conf
/usr/share/alsa/ucm2/codecs/rt5640/EnableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5640/IN3-InternalMic.conf
/usr/share/alsa/ucm2/codecs/rt5640/HeadPhones.conf
/usr/share/alsa/ucm2/codecs/rt5640/MonoSpeaker.conf
/usr/share/alsa/ucm2/codecs/rt5640/HeadsetMic.conf
/usr/share/alsa/ucm2/codecs/hda
/usr/share/alsa/ucm2/codecs/hda/hdmi.conf
/usr/share/alsa/ucm2/codecs/rt5682
/usr/share/alsa/ucm2/codecs/rt5682/init.conf
/usr/share/alsa/ucm2/codecs/nau8824
/usr/share/alsa/ucm2/codecs/nau8824/Speaker.conf
/usr/share/alsa/ucm2/codecs/nau8824/EnableSeq.conf
/usr/share/alsa/ucm2/codecs/nau8824/HeadPhones.conf
/usr/share/alsa/ucm2/codecs/nau8824/InternalMic.conf
/usr/share/alsa/ucm2/codecs/nau8824/MonoSpeaker.conf
/usr/share/alsa/ucm2/codecs/nau8824/HeadsetMic.conf
/usr/share/alsa/ucm2/codecs/cx2072x
/usr/share/alsa/ucm2/codecs/cx2072x/Speaker.conf
/usr/share/alsa/ucm2/codecs/cx2072x/EnableSeq.conf
/usr/share/alsa/ucm2/codecs/cx2072x/DisableSeq.conf
/usr/share/alsa/ucm2/codecs/cx2072x/HeadPhones.conf
/usr/share/alsa/ucm2/codecs/cx2072x/InternalMic.conf
/usr/share/alsa/ucm2/codecs/cx2072x/HeadsetMic.conf
/usr/share/alsa/ucm2/codecs/rt5672
/usr/share/alsa/ucm2/codecs/rt5672/Speaker.conf
/usr/share/alsa/ucm2/codecs/rt5672/EnableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5672/HeadPhones.conf
/usr/share/alsa/ucm2/codecs/rt5672/MonoSpeaker.conf
/usr/share/alsa/ucm2/codecs/rt5672/DMIC1.conf
/usr/share/alsa/ucm2/codecs/rt5672/HeadsetMic.conf
/usr/share/alsa/ucm2/codecs/rt5672/DMIC2.conf
/usr/share/alsa/ucm2/codecs/rt700
/usr/share/alsa/ucm2/codecs/rt700/init.conf
/usr/share/alsa/ucm2/codecs/rt5651
/usr/share/alsa/ucm2/codecs/rt5651/IN2-HeadsetMic.conf
/usr/share/alsa/ucm2/codecs/rt5651/IN12-InternalMic.conf
/usr/share/alsa/ucm2/codecs/rt5651/IN2-InternalMic.conf
/usr/share/alsa/ucm2/codecs/rt5651/IN1-InternalMic.conf
/usr/share/alsa/ucm2/codecs/rt5651/Speaker.conf
/usr/share/alsa/ucm2/codecs/rt5651/EnableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5651/HeadPhones.conf
/usr/share/alsa/ucm2/codecs/rt5651/MonoSpeaker.conf
/usr/share/alsa/ucm2/codecs/rt5651/HeadPhones-swapped.conf
/usr/share/alsa/ucm2/codecs/rt5651/DigitalMic.conf
/usr/share/alsa/ucm2/codecs/rt5651/IN3-HeadsetMic.conf
/usr/share/alsa/ucm2/codecs/rt5645
/usr/share/alsa/ucm2/codecs/rt5645/SpeakerEnableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5645/HSMicDisableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5645/HSMicEnableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5645/EnableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5645/DisableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5645/DigitalMicDisableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5645/AnalogMic.conf
/usr/share/alsa/ucm2/codecs/rt5645/HeadphonesEnableSeq.conf
/usr/share/alsa/ucm2/codecs/rt5645/DigitalMicEnableSeq.conf
/usr/share/alsa/ucm2/codecs/rt715-sdca
/usr/share/alsa/ucm2/codecs/rt715-sdca/init.conf
/usr/share/alsa/ucm2/codecs/es8316
/usr/share/alsa/ucm2/codecs/es8316/IN2-HeadsetMic.conf
/usr/share/alsa/ucm2/codecs/es8316/IN2-InternalMic.conf
/usr/share/alsa/ucm2/codecs/es8316/IN1-InternalMic.conf
/usr/share/alsa/ucm2/codecs/es8316/Speaker.conf
/usr/share/alsa/ucm2/codecs/es8316/EnableSeq.conf
/usr/share/alsa/ucm2/codecs/es8316/HeadPhones.conf
/usr/share/alsa/ucm2/codecs/es8316/MonoSpeaker.conf
/usr/share/alsa/ucm2/codecs/es8316/IN1-HeadsetMic.conf
/usr/share/alsa/ucm2/codecs/rt715
/usr/share/alsa/ucm2/codecs/rt715/init.conf
/usr/share/alsa/ucm2/chtrt5645
/usr/share/alsa/ucm2/chtrt5645/chtrt5645-dmic2.conf
/usr/share/alsa/ucm2/chtrt5645/chtrt5645.conf
/usr/share/alsa/ucm2/chtrt5645/gpd-win-pocket-rt5645.conf
/usr/share/alsa/ucm2/chtrt5645/ASUSTeKCOMPUTERINC.-T100HAN-1.0-T100HAN.conf
/usr/share/alsa/ucm2/chtrt5645/HiFi-dmic1.conf
/usr/share/alsa/ucm2/chtrt5645/HiFi-mono-speaker-analog-mic.conf
/usr/share/alsa/ucm2/chtrt5645/LENOVO-80XF-LenovoMIIX320_10ICR-LNVNB161216.conf
/usr/share/alsa/ucm2/chtrt5645/chtrt5645-mono-speaker-analog-mic.conf
/usr/share/alsa/ucm2/chtrt5645/HiFi.conf
/usr/share/alsa/ucm2/chtrt5645/TECLAST-X80Pro-Defaultstring-CherryTrailCR.conf
/usr/share/alsa/ucm2/chtrt5645/HiFi-dmic2.conf
/usr/share/alsa/ucm2/chtrt5645/chtrt5645-dmic1.conf
/usr/share/alsa/ucm2/module
/usr/share/alsa/ucm2/module/acp_pdm_mach.conf
/usr/share/alsa/ucm2/module/lib
/usr/share/alsa/ucm2/module/lib/linked.conf
/usr/share/alsa/ucm2/module/snd_acp3x_rn.conf
/usr/share/alsa/ucm2/DAISY-I2S
/usr/share/alsa/ucm2/DAISY-I2S/DAISY-I2S.conf
/usr/share/alsa/ucm2/DAISY-I2S/HiFi.conf
/usr/share/alsa/ucm2/bytcht-es8316
/usr/share/alsa/ucm2/bytcht-es8316/HiFi-Components.conf
/usr/share/alsa/ucm2/bytcht-es8316/bytcht-es8316.conf
/usr/share/alsa/ucm2/bytcht-es8316/HiFi.conf
/usr/share/alsa/ucm2/bytcht-es8316/HiFi-LongName.conf
/usr/share/alsa/ucm2/sof-hda-dsp
/usr/share/alsa/ucm2/sof-hda-dsp/Hdmi.conf
/usr/share/alsa/ucm2/sof-hda-dsp/sof-hda-dsp.conf
/usr/share/alsa/ucm2/sof-hda-dsp/HiFi.conf
/usr/share/alsa/ucm2/sof-hda-dsp/HDA-Capture-value.conf
/usr/share/alsa/ucm2/broadwell-rt286
/usr/share/alsa/ucm2/broadwell-rt286/broadwell-rt286.conf
/usr/share/alsa/ucm2/broadwell-rt286/HiFi.conf
/usr/share/alsa/ucm2/DB820c
/usr/share/alsa/ucm2/DB820c/HDMI.conf
/usr/share/alsa/ucm2/DB820c/HiFi.conf
/usr/share/alsa/ucm2/DB820c/DB820c.conf
/usr/share/alsa/ucm2/VEYRON-I2S
/usr/share/alsa/ucm2/VEYRON-I2S/HiFi.conf
/usr/share/alsa/ucm2/VEYRON-I2S/VEYRON-I2S.conf
/usr/share/alsa/ucm2/bytcr-rt5651
/usr/share/alsa/ucm2/bytcr-rt5651/HiFi-Components.conf
/usr/share/alsa/ucm2/bytcr-rt5651/HiFi.conf
/usr/share/alsa/ucm2/bytcr-rt5651/HiFi-LongName.conf
/usr/share/alsa/ucm2/bytcr-rt5651/bytcr-rt5651.conf
/usr/share/alsa/ucm2/broxton-rt298
/usr/share/alsa/ucm2/broxton-rt298/Hdmi.conf
/usr/share/alsa/ucm2/broxton-rt298/broxton-rt298.conf
/usr/share/alsa/ucm2/broxton-rt298/HiFi.conf
/usr/share/alsa/ucm2/PandaBoardES
/usr/share/alsa/ucm2/PandaBoardES/VoiceCall.conf
/usr/share/alsa/ucm2/PandaBoardES/PandaBoardES.conf
/usr/share/alsa/ucm2/PandaBoardES/Voice.conf
/usr/share/alsa/ucm2/PandaBoardES/HiFi.conf
/usr/share/alsa/ucm2/PandaBoardES/FMAnalog.conf
/usr/share/alsa/ucm2/PandaBoardES/Record.conf
/usr/share/alsa/ucm2/PandaBoardES/HiFiLP.conf
/usr/share/alsa/ucm2/chtnau8824
/usr/share/alsa/ucm2/chtnau8824/chtnau8824.conf
/usr/share/alsa/ucm2/chtnau8824/cube-i1_TF-Defaultstring-CherryTrailCR.conf
/usr/share/alsa/ucm2/chtnau8824/chtnau8824-mono.conf
/usr/share/alsa/ucm2/chtnau8824/HiFi.conf
/usr/share/alsa/ucm2/chtnau8824/HiFi-mono.conf
/usr/share/alsa/ucm2/chtnau8824/PIPO-W2S-Defaultstring-CherryTrailCR.conf
/usr/share/alsa/ucm2/skylake-rt286
/usr/share/alsa/ucm2/skylake-rt286/Hdmi2.conf
/usr/share/alsa/ucm2/skylake-rt286/Hdmi1.conf
/usr/share/alsa/ucm2/skylake-rt286/skylake-rt286.conf
/usr/share/alsa/ucm2/skylake-rt286/HiFi.conf
/usr/share/alsa/ucm2/platforms
/usr/share/alsa/ucm2/platforms/bytcr
/usr/share/alsa/ucm2/platforms/bytcr/PlatformEnableSeq.conf
/usr/share/alsa/ucm2/platforms/bytcr/PlatformDisableSeq.conf
/usr/share/alsa/ucm2/kblrt5660
/usr/share/alsa/ucm2/kblrt5660/Hdmi2.conf
/usr/share/alsa/ucm2/kblrt5660/kblrt5660.conf
/usr/share/alsa/ucm2/kblrt5660/Hdmi1.conf
/usr/share/alsa/ucm2/kblrt5660/HiFi.conf
/usr/share/alsa/ucm2/ucm.conf
/usr/share/alsa/ucm2/PandaBoard
/usr/share/alsa/ucm2/PandaBoard/VoiceCall.conf
/usr/share/alsa/ucm2/PandaBoard/PandaBoard.conf
/usr/share/alsa/ucm2/PandaBoard/Voice.conf
/usr/share/alsa/ucm2/PandaBoard/HiFi.conf
/usr/share/alsa/ucm2/PandaBoard/FMAnalog.conf
/usr/share/alsa/ucm2/PandaBoard/Record.conf
/usr/share/alsa/ucm2/PandaBoard/HiFiLP.conf
/usr/share/alsa/ucm2/DB410c
/usr/share/alsa/ucm2/DB410c/DB410c.conf
/usr/share/alsa/ucm2/DB410c/HDMI.conf
/usr/share/alsa/ucm2/DB410c/HiFi.conf
/usr/share/alsa/ucm2/PAZ00
/usr/share/alsa/ucm2/PAZ00/PAZ00.conf
/usr/share/alsa/ucm2/PAZ00/HiFi.conf
/usr/share/alsa/ucm2/PAZ00/Record.conf
/usr/share/alsa/ucm2/bytcht-cx2072x
/usr/share/alsa/ucm2/bytcht-cx2072x/bytcht-cx2072x.conf
/usr/share/alsa/ucm2/bytcht-cx2072x/HiFi.conf
/usr/share/alsa/ucm2/USB-Audio
/usr/share/alsa/ucm2/USB-Audio/Lenovo-ThinkStation-P620-Main-Speaker.conf
/usr/share/alsa/ucm2/USB-Audio/Lenovo-ThinkStation-P620-Main.conf
/usr/share/alsa/ucm2/USB-Audio/Dell-WD15-Dock-HiFi.conf
/usr/share/alsa/ucm2/USB-Audio/Lenovo-ThinkStation-P620-Rear.conf
/usr/share/alsa/ucm2/USB-Audio/Lenovo-ThinkStation-P620-Main-Headset.conf
/usr/share/alsa/ucm2/USB-Audio/Lenovo-ThinkStation-P620-Rear-Speaker.conf
/usr/share/alsa/ucm2/USB-Audio/Dell-WD15-Dock.conf
/usr/share/alsa/ucm2/USB-Audio/Lenovo-ThinkStation-P620-Rear-Line.conf
/usr/share/alsa/ucm2/USB-Audio/Lenovo-ThinkStation-P620-Rear-Mic.conf
/usr/share/alsa/ucm2/chtrt5650
/usr/share/alsa/ucm2/chtrt5650/chtrt5650.conf
/usr/share/alsa/ucm2/chtrt5650/HiFi.conf
/usr/share/alsa/ucm2/bytcr-rt5640
/usr/share/alsa/ucm2/bytcr-rt5640/HiFi-Components.conf
/usr/share/alsa/ucm2/bytcr-rt5640/HiFi.conf
/usr/share/alsa/ucm2/bytcr-rt5640/bytcr-rt5640.conf
/usr/share/alsa/ucm2/bytcr-rt5640/HiFi-LongName.conf
/usr/share/alsa/ucm2/tegraalc5632
/usr/share/alsa/ucm2/tegraalc5632/tegraalc5632.conf
/usr/share/alsa/ucm2/cht-bsw-rt5672
/usr/share/alsa/ucm2/cht-bsw-rt5672/LENOVO-20BN002QGE-ThinkPad8.conf
/usr/share/alsa/ucm2/cht-bsw-rt5672/cht-bsw-rt5672.conf
/usr/share/alsa/ucm2/cht-bsw-rt5672/HiFi.conf
/usr/share/alsa/ucm2/cht-bsw-rt5672/HiFi-stereo-dmic2.conf
/usr/share/alsa/ucm2/cht-bsw-rt5672/cht-bsw-rt5672-stereo-dmic2.conf
/usr/share/alsa/ucm2/cht-bsw-rt5672/LENOVO-20BN002QGE-ThinkPad8-20BN002QGE.conf
/usr/share/alsa/ucm2/HDA-Intel
/usr/share/alsa/ucm2/HDA-Intel/Hdmi.conf
/usr/share/alsa/ucm2/HDA-Intel/HDAudio-Lenovo-DualCodecs.conf
/usr/share/alsa/ucm2/HDA-Intel/HiFi-acp.conf
/usr/share/alsa/ucm2/HDA-Intel/HiFi-dual.conf
/usr/share/alsa/ucm2/HDA-Intel/HDA-Intel.conf
/usr/share/alsa/ucm2/HDA-Intel/HDAudio-Gigabyte-ALC1220DualCodecs.conf
/usr/share/alsa/ucm2/HDA-Intel/HiFi-analog.conf
/usr/share/alsa/ucm2/HDA-Intel/init.conf
/usr/share/alsa/ucm2/HDA-Intel/HDAudio-DualCodecs.conf
/usr/share/alsa/ucm2/HDA-Intel/HiFi.conf
/usr/share/alsa/ucm2/HDA-Intel/HDA-Capture-value.conf
/usr/share/alsa/ucm2/SDP4430
/usr/share/alsa/ucm2/SDP4430/VoiceCall.conf
/usr/share/alsa/ucm2/SDP4430/SDP4430.conf
/usr/share/alsa/ucm2/SDP4430/Voice.conf
/usr/share/alsa/ucm2/SDP4430/HiFi.conf
/usr/share/alsa/ucm2/SDP4430/FMAnalog.conf
/usr/share/alsa/ucm2/SDP4430/Record.conf
/usr/share/alsa/ucm2/SDP4430/HiFiLP.conf
/usr/share/alsa/ucm2/README.md
/usr/share/alsa/ucm2/GoogleNyan
/usr/share/alsa/ucm2/GoogleNyan/GoogleNyan.conf
/usr/share/alsa/ucm2/GoogleNyan/HiFi.conf
/usr/share/alsa/ucm2/sof-soundwire
/usr/share/alsa/ucm2/sof-soundwire/Hdmi.conf
/usr/share/alsa/ucm2/sof-soundwire/rt1316-1.conf
/usr/share/alsa/ucm2/sof-soundwire/rt715-sdca.conf
/usr/share/alsa/ucm2/sof-soundwire/rt1308-1.conf
/usr/share/alsa/ucm2/sof-soundwire/sof-soundwire.conf
/usr/share/alsa/ucm2/sof-soundwire/rt711.conf
/usr/share/alsa/ucm2/sof-soundwire/rt711-sdca.conf
/usr/share/alsa/ucm2/sof-soundwire/rt5682.conf
/usr/share/alsa/ucm2/sof-soundwire/rt700.conf
/usr/share/alsa/ucm2/sof-soundwire/rt715.conf
/usr/share/alsa/ucm2/sof-soundwire/rt1316-2.conf
/usr/share/alsa/ucm2/sof-soundwire/HiFi.conf
/usr/share/alsa/ucm2/sof-soundwire/rt1308-2.conf

_fdisk -l_
Disk /dev/loop0: 61.85 MiB, 64835584 bytes, 126632 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/loop1: 61.93 MiB, 64913408 bytes, 126784 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/loop2: 67.25 MiB, 70508544 bytes, 137712 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/loop3: 42.18 MiB, 44220416 bytes, 86368 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/loop4: 43.28 MiB, 45371392 bytes, 88616 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/mmcblk0: 116.5 GiB, 125074145280 bytes, 244285440 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 2C8B0BF0-B47D-479B-A47E-48D3D87CEADE

Device          Start       End   Sectors   Size Type
/dev/mmcblk0p1   2048    133119    131072    64M ChromeOS kernel
/dev/mmcblk0p2 133120 244283391 244150272 116.4G Linux filesystem

**Comment by ArtemPozharov** [comment]
I am his friend and also cannot to solve this problem. setup-audio doesn't work. You use the same Chromebook. How did you enable the audio?

**Comment by MilkyDeveloper** [comment]
@IvanFonarev You can find the files separately in the Nami recovery image. However, I'd recommend restoring the system from the recovery image and then enabling developer mode.
