### ISSUE TITLE
Wifi not working OOTB 

### ISSUE THREAD

**Issue by J0shuaT** [MilkyDeveloper/cb-linux#13]
My Wifi is not working upon first boot. This prevents me from updating packages/updates. Is there anything I need to do?

**Comment by MilkyDeveloper** [comment]
What is your chromebook model? Can you post the output of `lspci -v` and `lsmod` from ChromeOS?

**Comment by J0shuaT** [comment]
where do I paste those commands? Shell says "command not found"

**Comment by J0shuaT** [comment]
Ok sorry lol i found it
**LSMOD:**

Module                  Size  Used by
snd_seq_dummy          16384  0
snd_seq                57344  5 snd_seq_dummy
snd_seq_device         16384  1 snd_seq
bridge                110592  0
stp                    16384  1 bridge
llc                    16384  2 bridge,stp
tun                    36864  0
nf_nat_tftp            16384  0
nf_conntrack_tftp      16384  1 nf_nat_tftp
nf_nat_ftp             16384  0
nf_conntrack_ftp       16384  1 nf_nat_ftp
xfrm6_mode_tunnel      16384  0
xfrm6_mode_transport    16384  0
xfrm4_mode_tunnel      16384  0
xfrm4_mode_transport    16384  0
esp6                   20480  0
ah6                    16384  0
ip6t_REJECT            16384  2
ip6t_ipv6header        16384  0
vhost_vsock            20480  5
vhost                  36864  1 vhost_vsock
vmw_vsock_virtio_transport_common    24576  1 vhost_vsock
vsock                  36864  7 vmw_vsock_virtio_transport_common,vhost_vsock
8021q                  28672  0
ccm                    20480  6
veth                   16384  0
rfcomm                 45056  2
cmac                   16384  3
algif_hash             16384  1
algif_skcipher         16384  1
af_alg                 20480  6 algif_hash,algif_skcipher
xt_cgroup              16384  2
uinput                 20480  0
ipt_MASQUERADE         16384  1
nf_nat_masquerade_ipv4    16384  1 ipt_MASQUERADE
xt_mark                16384  96
btusb                  45056  0
btrtl                  16384  1 btusb
btintel                24576  1 btusb
btbcm                  16384  1 btusb
bluetooth             442368  32 btrtl,btintel,btbcm,btusb,rfcomm
ecdh_generic           24576  1 bluetooth
snd_soc_sst_bxt_da7219_max98357a    24576  4
snd_soc_hdac_hdmi      28672  1 snd_soc_sst_bxt_da7219_max98357a
snd_soc_dmic           16384  1
sof_pci_dev            16384  2
snd_sof_xtensa_dsp     16384  1 sof_pci_dev
snd_sof_intel_hda_common    49152  1 sof_pci_dev
snd_sof_intel_hda      16384  1 snd_sof_intel_hda_common
snd_soc_hdac_hda       20480  1 snd_sof_intel_hda_common
snd_sof                73728  2 snd_sof_intel_hda_common,sof_pci_dev
snd_soc_acpi_intel_match    28672  2 snd_sof_intel_hda_common,sof_pci_dev
snd_soc_acpi           16384  2 snd_soc_acpi_intel_match,sof_pci_dev
snd_hda_ext_core       20480  4 snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_soc_hdac_hda,snd_sof_intel_hda
snd_hda_codec         106496  1 snd_soc_hdac_hda
snd_hwdep              16384  1 snd_hda_codec
snd_hda_core           61440  6 snd_hda_ext_core,snd_hda_codec,snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_soc_hdac_hda,snd_sof_intel_hda
snd_soc_max98357a      16384  1
snd_soc_da7219         65536  2 snd_soc_sst_bxt_da7219_max98357a
ip6table_nat           16384  1
nf_nat_ipv6            16384  1 ip6table_nat
fuse                  102400  20
lzo_rle                16384  2
lzo_compress           16384  1 lzo_rle
zram                   20480  1
rtw88_8822ce           16384  0
rtw88_pci              24576  1 rtw88_8822ce
rtw88_8822c           487424  1 rtw88_8822ce
rtw88_core            172032  2 rtw88_pci,rtw88_8822c
mac80211              630784  2 rtw88_pci,rtw88_core
cfg80211              536576  2 rtw88_core,mac80211
uvcvideo               86016  0
videobuf2_vmalloc      16384  1 uvcvideo
joydev                 24576  0

**LSPCI -V**

snd_seq_dummy          16384  0
snd_seq                57344  5 snd_seq_dummy
snd_seq_device         16384  1 snd_seq
bridge                110592  0
stp                    16384  1 bridge
llc                    16384  2 bridge,stp
tun                    36864  0
nf_nat_tftp            16384  0
nf_conntrack_tftp      16384  1 nf_nat_tftp
nf_nat_ftp             16384  0
nf_conntrack_ftp       16384  1 nf_nat_ftp
xfrm6_mode_tunnel      16384  0
xfrm6_mode_transport    16384  0
xfrm4_mode_tunnel      16384  0
xfrm4_mode_transport    16384  0
esp6                   20480  0
ah6                    16384  0
ip6t_REJECT            16384  2
ip6t_ipv6header        16384  0
vhost_vsock            20480  5
vhost                  36864  1 vhost_vsock
vmw_vsock_virtio_transport_common    24576  1 vhost_vsock
vsock                  36864  7 vmw_vsock_virtio_transport_common,vhost_vsock
8021q                  28672  0
ccm                    20480  6
veth                   16384  0
rfcomm                 45056  2
cmac                   16384  3
algif_hash             16384  1
algif_skcipher         16384  1
af_alg                 20480  6 algif_hash,algif_skcipher
xt_cgroup              16384  2
uinput                 20480  0
ipt_MASQUERADE         16384  1
nf_nat_masquerade_ipv4    16384  1 ipt_MASQUERADE
xt_mark                16384  96
btusb                  45056  0
btrtl                  16384  1 btusb
btintel                24576  1 btusb
btbcm                  16384  1 btusb
bluetooth             442368  32 btrtl,btintel,btbcm,btusb,rfcomm
ecdh_generic           24576  1 bluetooth
snd_soc_sst_bxt_da7219_max98357a    24576  4
snd_soc_hdac_hdmi      28672  1 snd_soc_sst_bxt_da7219_max98357a
snd_soc_dmic           16384  1
sof_pci_dev            16384  2
snd_sof_xtensa_dsp     16384  1 sof_pci_dev
snd_sof_intel_hda_common    49152  1 sof_pci_dev
snd_sof_intel_hda      16384  1 snd_sof_intel_hda_common
snd_soc_hdac_hda       20480  1 snd_sof_intel_hda_common
snd_sof                73728  2 snd_sof_intel_hda_common,sof_pci_dev
snd_soc_acpi_intel_match    28672  2 snd_sof_intel_hda_common,sof_pci_dev
snd_soc_acpi           16384  2 snd_soc_acpi_intel_match,sof_pci_dev
snd_hda_ext_core       20480  4 snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_soc_hdac_hda,snd_sof_intel_hda
snd_hda_codec         106496  1 snd_soc_hdac_hda
snd_hwdep              16384  1 snd_hda_codec
snd_hda_core           61440  6 snd_hda_ext_core,snd_hda_codec,snd_sof_intel_hda_common,snd_soc_hdac_hdmi,snd_soc_hdac_hda,snd_sof_intel_hda
snd_soc_max98357a      16384  1
snd_soc_da7219         65536  2 snd_soc_sst_bxt_da7219_max98357a
ip6table_nat           16384  1
nf_nat_ipv6            16384  1 ip6table_nat
fuse                  102400  20
lzo_rle                16384  2
lzo_compress           16384  1 lzo_rle
zram                   20480  1
rtw88_8822ce           16384  0
rtw88_pci              24576  1 rtw88_8822ce
rtw88_8822c           487424  1 rtw88_8822ce
rtw88_core            172032  2 rtw88_pci,rtw88_8822c
mac80211              630784  2 rtw88_pci,rtw88_core
cfg80211              536576  2 rtw88_core,mac80211
uvcvideo               86016  0
videobuf2_vmalloc      16384  1 uvcvideo
joydev                 24576  0

**Comment by MilkyDeveloper** [comment]
Alright, I know how to fix it. Thanks for the info. Expect a fix by the end of the week.

**Comment by J0shuaT** [comment]
Thanks!

**Comment by J0shuaT** [comment]
Is there a way to install a few apps until then?

**Comment by MilkyDeveloper** [comment]
Fixed, plug in the USB and run:
```
bash updatekernel.sh
```
on your Linux computer (not the Chromebook)
