### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by QL100100** [MilkyDeveloper/cb-linux#15]
I Got this error when directing breath to write to my USB drive
I'm doing this on Debian 11 LXterminal, installed on my Acer Chromebook Spin 11 with crouton.

umount: /mnt: not mounted.
umount: /mnt: not mounted.
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by MilkyDeveloper** [comment]
I don't think Crouton works but try doing `sudo rm -rf ~/linux-build` and then rerun the script.
