### ISSUE TITLE
Wifi still not working after update. Octopus chromebook

### ISSUE THREAD

**Issue by J0shuaT** [MilkyDeveloper/cb-linux#19]
(url
![IMG_0622](https://user-images.githubusercontent.com/96457853/147394242-88a80bc8-7f62-4f57-9df4-2c2995dbefc3.jpeg)
)

**Comment by MilkyDeveloper** [comment]
Please follow [these instructions](https://kb.iu.edu/d/bdxq) within ChromeOS

**Comment by J0shuaT** [comment]
Here is the info:

00:00.0 Host bridge: Intel Corporation Device 31f0 (rev 06) 00:00.1 Signal processing controller: Intel Corporation Device 318c (rev 06) 00:02.0 VGA compatible controller: Intel Corporation Device 3185 (rev 06) 00:0e.0 Multimedia audio controller: Intel Corporation Device 3198 (rev 06) 00:13.0 PCI bridge: Intel Corporation Device 31d8 (rev f6) 00:15.0 USB controller: Intel Corporation Device 31a8 (rev 06) 00:17.0 Signal processing controller: Intel Corporation Device 31b4 (rev 06) 00:17.1 Signal processing controller: Intel Corporation Device 31b6 (rev 06) 00:17.2 Signal processing controller: Intel Corporation Device 31b8 (rev 06) 00:17.3 Signal processing controller: Intel Corporation Device 31ba (rev 06) 00:18.0 Signal processing controller: Intel Corporation Device 31bc (rev 06) 00:18.2 Signal processing controller: Intel Corporation Device 31c0 (rev 06) 00:19.0 Signal processing controller: Intel Corporation Device 31c2 (rev 06) 00:19.2 Signal processing controller: Intel Corporation Device 31c6 (rev 06) 00:1c.0 SD Host controller: Intel Corporation Device 31cc (rev 06) 00:1f.0 ISA bridge: Intel Corporation Device 3197 (rev 06) 00:1f.1 SMBus: Intel Corporation Device 31d4 (rev 06) 01:00.0 Network controller: Realtek Semiconductor Co., Ltd. Device c822

Merry Christmas!

**Comment by MilkyDeveloper** [comment]
Thanks :D. Merry Christmas to you too! Try running `sudo modprobe rtw_8822ce` to fix Wifi.

**Comment by MilkyDeveloper** [comment]
Reminder to self: incorporate module into `/etc/modules`

**Comment by J0shuaT** [comment]
I tried it and got this: `FATAL: Module rtw_8822ce not found in directory /lib/modules/5.4.165`

**Comment by MilkyDeveloper** [comment]
Plug in a USB and try running `bash updatekernel.sh` on your Linux PC (the one you built Breath with). Let me know if you need to run `modprobe`.

**Comment by J0shuaT** [comment]
Do I plug in the same USB I have Breath installed on? Also, do I need to run `bash updatekernel.sh` in a certain directory?

**Comment by MilkyDeveloper** [comment]
Yes, you plug in the same USB. You need to run `bash updatekernel.sh` in the same place you ran `bash setup.sh gnome ubuntu`

**Comment by adog9712** [comment]
Hi,

I have got the same problem and my Chromebook's WIFI card is the same as this one. I have done bash updatekernel.sh and done the modprobe command and still have no WiFi. The modbprobe command does not work as it returns sudo: modprobe: command not found.

**Comment by MilkyDeveloper** [comment]
@adog9712 How can the command `modprobe` not be found? It is installed by default on all distros. What distro did you install and what is your chromebook? You need to run modprobe on the chromebook booted of the Breath USB.

**Comment by adog9712** [comment]
I installed Ubuntu 18.04.06 LTS. My Chromebook is HP Chromebook 14a. I ran
the command from a freshly opened terminal on the Chromebook.

**Comment by adog9712** [comment]
Do I need to run from a specific directory on the Chromebook?

**Comment by MilkyDeveloper** [comment]
What did you install Ubuntu 18.04 on? Crouton does not work with this project. You do not run any commands of the chromebook, you need to boot the USB you built from a non-chromebook).

**Comment by adog9712** [comment]
I installed Ubuntu 18.04 onto a USB from a laptop running linux. And then
booted the Chromebook up from the USB and tried the and within the Ubuntu
booted up from the USB. I am running a HP Chromebook 14a.

**Comment by MilkyDeveloper** [comment]
So on the Chromebook booted with Breath, is there no `modprobe` command? If so, I don't think Breath has been installed correctly.

**Comment by adog9712** [comment]
Got Modprobe working now.

Get the following error when running sudo modprobe rtw_8822ce.  

modprobe: FATAL: Module rtw_8822ce not found in directory /lib/modules/5.10.88

**Comment by MilkyDeveloper** [comment]
@J0shuaT and @adog9712: Plug in the Breath USB and try running `bash updatekernel.sh`. It seems like it was an error on my end :D

**Comment by J0shuaT** [comment]
Thanks, Wifi is working perfectly now! Even Bluetooth works! Now all I have left to do is get my audio working. Isn't there a command I need to run to get the audio working?

**Comment by MilkyDeveloper** [comment]
Yes, since you have an Octopus chromebook, you just need to run ‘sof-setup-audio’

**Comment by J0shuaT** [comment]
Surprisingly, the Wifi working immediately without the modprobe command.
