### ISSUE TITLE
cb-linux/breath future

### ISSUE THREAD

**Issue by hede5562** [MilkyDeveloper/cb-linux#2]
As the referenced project [cb-linux/breath](https://github.com/cb-linux/breath) already is archived and github doesn't offer a private message functionality I do ask this question here and in public: 

Do you know of any fork/successor where new contributions to the project can go on? Do you know which of the forks is the most active one?

**Comment by MilkyDeveloper** [comment]
Most definetly https://github.com/eupnea-linux/eupnea. We have lots of discussion over on the Discord.

**Comment by hede5562** [comment]
Thanks for your answer. That seems to be what I was searching for. Maybe it's worth a mentioning in the archived cb-linux/breath project readme?

**Comment by hede5562** [comment]
PS: I see there's the discord thread linked. Sorry, I missed that. (I'm not a discord user)
