### ISSUE TITLE
Can you bring audio to Apollo Lake devices?

### ISSUE THREAD

**Issue by QL100100** [MilkyDeveloper/cb-linux#20]
On my previous posts I forgot to thank you for your amazing contribution to the Chrome OS community.
Can you bring audio to Apollo Lake Chromebooks?
I'm using an Acer Chromebook Spin 11(2018) and would like to use my speakers and microphone for video chats on Ubuntu.
Or are there any workarounds? The commands on your website don't work on my Chromebook.
Thanks

**Comment by MilkyDeveloper** [comment]
Could you try running lsmod within the ChromeOS shell?

**Comment by MilkyDeveloper** [comment]
You might get audio working by running `sof-setup-audio` within Breath on your chromebook.

**Comment by QL100100** [comment]
lsmod output:
Module                  Size  Used by
snd_seq_dummy          16384  0
snd_seq                57344  5 snd_seq_dummy
snd_seq_device         16384  1 snd_seq
bridge                 94208  0
stp                    16384  1 bridge
llc                    16384  2 stp,bridge
tun                    28672  0
nf_nat_tftp            16384  0
nf_conntrack_tftp      16384  1 nf_nat_tftp
nf_nat_ftp             16384  0
nf_conntrack_ftp       16384  1 nf_nat_ftp
xfrm6_mode_tunnel      16384  0
xfrm6_mode_transport    16384  0
xfrm4_mode_tunnel      16384  0
xfrm4_mode_transport    16384  0
esp6                   16384  0
ah6                    16384  0
ip6t_REJECT            16384  2
nf_reject_ipv6         16384  1 ip6t_REJECT
ip6t_ipv6header        16384  0
ccm                    20480  1
vhost_vsock            20480  5
vmw_vsock_virtio_transport_common    20480  1 vhost_vsock
vsock                  32768  7 vmw_vsock_virtio_transport_common,vhost_vsock
vhost                  24576  1 vhost_vsock
veth                   16384  0
rfcomm                 40960  2
cmac                   16384  2
algif_hash             16384  1
algif_skcipher         20480  1
af_alg                 16384  6 algif_hash,algif_skcipher
xt_cgroup              16384  2
uinput                 20480  0
ipt_MASQUERADE         16384  1
nf_nat_masquerade_ipv4    16384  1 ipt_MASQUERADE
xt_mark                16384  96
iio_trig_hrtimer       16384  2
industrialio_sw_trigger    16384  1 iio_trig_hrtimer
industrialio_configfs    16384  2 industrialio_sw_trigger
snd_soc_sst_bxt_da7219_max98357a    24576  4
snd_soc_hdac_hdmi      24576  1 snd_soc_sst_bxt_da7219_max98357a
snd_soc_dmic           16384  1
snd_soc_skl_ssp_clk    16384  0
acpi_als               16384  1
snd_soc_max98357a      16384  1
snd_soc_da7219         53248  2 snd_soc_sst_bxt_da7219_max98357a
snd_soc_skl            65536  3 snd_soc_skl_ssp_clk
snd_soc_skl_ipc        36864  1 snd_soc_skl
snd_soc_sst_dsp        32768  1 snd_soc_skl_ipc
snd_soc_sst_ipc        16384  1 snd_soc_skl_ipc
snd_soc_sst_match      16384  1 snd_soc_skl
snd_hda_ext_core       20480  2 snd_soc_hdac_hdmi,snd_soc_skl
snd_hda_core           53248  3 snd_hda_ext_core,snd_soc_hdac_hdmi,snd_soc_skl
ip6table_nat           16384  1
nf_nat_ipv6            16384  1 ip6table_nat
fuse                   90112  20
ip6table_filter        16384  2
iio_trig_sysfs         16384  0
cros_ec_sensors        16384  2
cros_ec_sensors_core    16384  1 cros_ec_sensors
industrialio_triggered_buffer    16384  2 cros_ec_sensors_core,acpi_als
kfifo_buf              16384  2 industrialio_triggered_buffer,cros_ec_sensors_core
industrialio           49152  9 iio_trig_hrtimer,industrialio_triggered_buffer,iio_trig_sysfs,cros_ec_sensors_core,acpi_als,kfifo_buf,cros_ec_sensors
cros_ec_sensorhub      20480  1 cros_ec_sensors_core
iwlmvm                409600  0
iwlwifi               344064  1 iwlmvm
iwl7000_mac80211      655360  2 iwlwifi,iwlmvm
zram                   24576  1
cfg80211              479232  3 iwlwifi,iwlmvm,iwl7000_mac80211
btusb                  40960  0
btrtl                  16384  1 btusb
btintel                24576  1 btusb
btbcm                  16384  1 btusb
bluetooth             413696  32 btbcm,btrtl,btusb,rfcomm,btintel
uvcvideo               81920  0
videobuf2_vmalloc      16384  1 uvcvideo
videobuf2_v4l2         24576  1 uvcvideo
videobuf2_core         28672  2 uvcvideo,videobuf2_v4l2
videobuf2_memops       16384  1 videobuf2_vmalloc
joydev                 20480  0

**Comment by MilkyDeveloper** [comment]
You might have some luck by running `sof-setup-audio`

**Comment by QL100100** [comment]
I tried that and got this error:


Package firmware-sof-signed is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'firmware-sof-signed' has no installation candidate
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package firmware-sof-signed is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'firmware-sof-signed' has no installation candidate

**Comment by MilkyDeveloper** [comment]
It seems like your Ubuntu version is a bit old. I've updated the default Ubuntu version to one that is compatible with the sof script, and you can upgrade to it by running: `sudo do-release-upgrade` on Breath or reinstalling it. Then try running the `sof-setup-audio` script.

**Comment by QL100100** [comment]
Thank you, it worked after updating
