### ISSUE TITLE
OS Shuts Down when Laptop lid is closed

### ISSUE THREAD

**Issue by J0shuaT** [MilkyDeveloper/cb-linux#23]
I have this weird bug when I close the lid of my laptop, the whole Ubuntu OS shuts down leaving me with a black screen. It thens shows the OS Verification screen. This also happens when I press suspend on Ubuntu.

**Comment by MilkyDeveloper** [comment]
This is a kernel bug, out of my hands to fix.

**Comment by J0shuaT** [comment]
So is this specific to my device?

**Comment by MilkyDeveloper** [comment]
Yes.

**Comment by MilkyDeveloper** [comment]
Issue moved to #29
