### ISSUE TITLE
Audio for Acer Chromebook Spin 514 (Zork, Ryzen 3 3250C)

### ISSUE THREAD

**Issue by wrigglevision** [MilkyDeveloper/cb-linux#24]
[lsmod.txt](https://github.com/MilkyDeveloper/cb-linux/files/7786255/lsmod.txt)
[findalsa.txt](https://github.com/MilkyDeveloper/cb-linux/files/7786256/findalsa.txt)

AMD audio coprocessor 3.x
RT5682
MAX98357

**Comment by MilkyDeveloper** [comment]
Plug in the Breath USB into your Linux PC (not the chromebook) try running `bash updatekernel.sh`.

**Comment by wrigglevision** [comment]
Success! 

Card/Device is now recognized. I’ll play around with apulse and ucm in a moment.

**Comment by MilkyDeveloper** [comment]
Nice! I’ve already made a script that automates UCM/apulse, you just need to run ‘sof-setup-audio’ on Breath booted on the chromebook.
