### ISSUE TITLE
Linux Breath USB builder does not work

### ISSUE THREAD

**Issue by abrahamchapman** [MilkyDeveloper/cb-linux#25]
The computer with which I am building a Linux Breath bootable USB is running the latest Linux Mint xfce.

When the Breath builder gets to "Which USB Drive or SD Card would you like to use (e.g. /dev/sda)? All data on the drive will be wiped!"
"sdb   DataTraveler_3.0            usb" is displayed.

When I type "/dev/sdb" and hit the Enter button, the following error message is displayed, and nothing is installed onto the USB disk.

Ok, using dev/sdb to install Linux
unmount: dev/sdb*:no mount point specified
unmount: /mnt: not mounted.
unmount: /media/*/*: no mount point specified.
Error: Could not stat device dev/sdb - No such file or directory

**Comment by MilkyDeveloper** [comment]
You forgot the slash - you typed in “dev/sdb” instead of “/dev/sdb”
