### ISSUE TITLE
Touchpad Doesn't Work on Acer Chromebook Spin 11

### ISSUE THREAD

**Issue by QL100100** [MilkyDeveloper/cb-linux#26]
On my Chromebook, the touchpad works in a breath install of LXQT, but not XFCE.
Can you help me fix this, or do I need to install drivers?
I'm doing this on an Acer Chromebook Spin 11(REEF)

**Comment by MilkyDeveloper** [comment]
This isn’t a kernel issue (which is what this project focuses over), it depends on the desktop environment, which is out of my hands. I recommend you look at general troubleshooting steps for touchpads. Maybe I’ve updated the kernel between the installs, so just to be sure, try reinstalling XFCE.
