### ISSUE TITLE
Worse Performance than Crostini Linux

### ISSUE THREAD

**Issue by J0shuaT** [MilkyDeveloper/cb-linux#28]
I'm not sure why, but I am experiencing lower performance in applications than on Crostini linux. For example, I installed Blender on Ubuntu and experienced a lot of lag and input delay. When I ran Blender on Crostini, I did not have these issues. I ran `glxinfo -B` on Ubuntu, and it shows GPU acceleration. I'm confused 🤷🏾‍♂

**Comment by J0shuaT** [comment]
What is the userspace label for? Is there something I need to fix on my end?

**Comment by MilkyDeveloper** [comment]
The userspace label shows a problem with Linux, not the kernel. Although, it might be the kernel now that I think about it. Don't worry about it.

**Comment by MilkyDeveloper** [comment]
I've never experienced any such issues. Since it's a userspace issue, it's a problem of the distro (Ubuntu). Try troubleshooting using posts like: [https://www.reddit.com/r/linuxquestions/comments/dq8vda/blenders_slow_ui_performance_in_linux/](https://www.reddit.com/r/linuxquestions/comments/dq8vda/blenders_slow_ui_performance_in_linux/).

**Comment by J0shuaT** [comment]
Blender wasn't the only application with these issues. I ran a Steam game called `Maker King` on the lowest settings and only got `2 FPS`. When I ran the same game with the same settings on Crostini I got roughly `35 FPS`. Should I just rebuild the USB?

**Comment by MilkyDeveloper** [comment]
I forgot, you still have it on a USB. This is the most likely cause. You probably have a slow USB. If possible, tell me the USB model. Either way, this issue is out of my hands, though I may consider a move to f2fs which is faster.

**Comment by J0shuaT** [comment]
I got my MicroSD card from here: https://www.microcenter.com/site/content/flashspecialoffer2.aspx#eduformdiv I am not sure of the model.

**Comment by MilkyDeveloper** [comment]
That is a very, very slow SD Card. Remember that you are booting an OS off of the SD Card, not playing videos off of it, the intended purpose.

**Comment by J0shuaT** [comment]
Yikes, I didn't know that. Maybe the USB would be considerably faster?

**Comment by J0shuaT** [comment]
Where are the instructions to install Breath via Crostini?

**Comment by MilkyDeveloper** [comment]
Currently, Crostini installs don't work. USB devices, or even a fast SD Card, would be good enough. I don't test this project on expensive USBs, instead I just use a generic Sandisk USB 3.0 Drive.

**Comment by J0shuaT** [comment]
I tried the USB and it was actually slower than the MicroSD. I'll just wait until Audio works so I can install to internal storage.
