### ISSUE TITLE
No Wifi on Debian

### ISSUE THREAD

**Issue by QL100100** [MilkyDeveloper/cb-linux#31]
I'm using a REEF Chromebook(Acer Chromebook Spin 11)
I got bored of Ubuntu, so I installed Debian
But the wifi card doesn't work! No networks were shown on the "Networks" window.
It's the same case on both XFCE and KDE, both with **firmware-iwlwifi** installed.
Is it an issue with Breath or have I missed any drivers?

**Comment by MilkyDeveloper** [comment]
Could you try installing Ubuntu and see if the problem persists?

**Comment by QL100100** [comment]
No, that error is nonexistent on Ubuntu.
But I really want to use Debian, it's the distro I was raised in.

**Comment by MilkyDeveloper** [comment]
Should be fixed now. If you don't want to reinstall Debian, just run:
```
sudo echo "iwlmvm" >> /etc/modules-load.d/modules.conf
```
:D

**Comment by ArakiSatoshi** [comment]
Sorry, I don't know if it's ok to write in a closed issue, but I have to mention it. I'm on a freshly installed Debian, Lenovo Chromebook C340. The wifi did not work initially. But it works now after running the mentioned command. So if there's something that should do it automatically during the installation, it doesn't.
