### ISSUE TITLE
Building USB installer fails with error

### ISSUE THREAD

**Issue by aghebert** [MilkyDeveloper/cb-linux#33]
Running Ubuntu 20.04 on a Macbook Pro (Early 2011 model)

When I try to run the setup.sh command, it will run through the installer, but after about ~10 it will fail with the following error:
```console
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/w/wpa/wpasupplicant_2.9.0-21_amd64.deb  Error reading from server - read (104: Connection reset by peer) [IP: 91.189.91.39 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

I cannot find any helpful information online about why this is happening.
This issue is also sudden, as I was able to build the USB fine just last week, but have had issues for about the last 5-7 days (I cannot recall when this started).

I have tried the following commands:

```console
bash setup.sh gnome ubuntu
bash setup.sh minimal ubuntu
bash setup.sh gnome focal-20.04
bash setup.sh minimal focal-20.04
```

All have failed with that specific error. Additionally, I have tried the previous commands on a Ubuntu 21.10 installation with similar results.

**Comment by MilkyDeveloper** [comment]
This also happens on my installer. Unfortunately, it's a problem with Ubuntu itself. I can download the same exact URL from my browser. Try rerunning the script after running `git fetch; git pull` within the Breath directory. You SHOULD NOT rerun Breath 4 times to test a bug, that will definitely wear out your USB.

**Comment by aghebert** [comment]
Unfortunately, I still get the same error after `git fetch; git pull`

**Comment by aghebert** [comment]
Wait. It made a mistake. It appears the error is now:
```console
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/n/network-manager/network-manager_1.30.0-1ubuntu3_amd64.deb  Error reading from server - read (104: Connection reset by peer) [IP: 91.189.88.142 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
I mistakenly thought it was still `wpasupplicant`

**Comment by MilkyDeveloper** [comment]
Nothing I can do about it.
