### ISSUE TITLE
no wi-fi on nami

### ISSUE THREAD

**Issue by ataro64** [MilkyDeveloper/cb-linux#38]
hello, i am not able to get wi-fi working on my nami. see attached pics.

![](https://files.catbox.moe/597506.jpeg)

![](https://files.catbox.moe/ed80rf.jpeg)

**Comment by MilkyDeveloper** [comment]
Post the output of `lsmod` and `dmesg` on your chromebook.

**Comment by ataro64** [comment]
sorry, i have fixed it, debian does not support my card but ubuntu does

**Comment by MilkyDeveloper** [comment]
Alright :D
