### ISSUE TITLE
Feature Request: Debian Release

### ISSUE THREAD

**Issue by ChrisTitusTech** [MilkyDeveloper/cb-linux#4]
I would love to see a Debian script added to the /utils/distros selection.

**Comment by MilkyDeveloper** [comment]
I’ve added a commit that adds half of what’s needed to debootstrap Debian :D. I’ll probably get it working by tomorrow morning. It’s such an honor to be acknowledged by you!

**Comment by ChrisTitusTech** [comment]
Thank you sir, this is an absolutely amazing project. You are doing a fantastic job!

**Comment by MilkyDeveloper** [comment]
I've added Debian support in the latest commit. After running `git fetch; git pull`, you can use 
```
bash setup.sh [DESKTOP (e.g. gnome or cli)] debian
```
to install Debian unstable.
