### ISSUE TITLE
Do not use apt in the script - list it as a dependency

### ISSUE THREAD

**Issue by KSPAtlas** [MilkyDeveloper/cb-linux#40]
Using apt in a script is unsupported, please list it as a dependency, this may also help make the program distro independent

**Comment by MilkyDeveloper** [comment]
I can’t support multiple distros. The maintenance cost is too high, and most people use Ubuntu anyways.

**Comment by KSPAtlas** [comment]
That is changing fast, and we could always help contribute for arch or void, I had to literally make a Debian VM for this

**Comment by MilkyDeveloper** [comment]
Yes, “you” could always help contribute :D
