### ISSUE TITLE
CAREENA - loud beep on ctrl-u

### ISSUE THREAD

**Issue by KSPAtlas** [MilkyDeveloper/cb-linux#41]
After flashing the USB stick via a Debian VM in QEMU, attempting to press ctrl-u on the Dev mode screen makes a very loud beep and resets the Chromebook.

**Comment by MilkyDeveloper** [comment]
There is already an issue tracking Careena, #17.

**Comment by KSPAtlas** [comment]
This is an unrelated issue, they just get a black screen

**Comment by MilkyDeveloper** [comment]
CTRL-U making a beep means your USB is malformed. Try rerunning the script. A black screen indicates that the USB has at-least booted.

**Comment by KSPAtlas** [comment]
> CTRL-U making a beep means your USB is malformed. Try rerunning the script. A black screen indicates that the USB has at-least booted.

Can I build from inside QEMU and if so, how? I don't run Debian/Ubuntu

**Comment by MilkyDeveloper** [comment]
You can run the script with the `FEATURES=ISO` environment variable within a VM, but make sure you know how to transfer the ISO file built out of the VM and into the host to flash it.

**Comment by KSPAtlas** [comment]
Turns out it was a flash issue
