### ISSUE TITLE
Installation questions

### ISSUE THREAD

**Issue by avram-meir** [MilkyDeveloper/cb-linux#44]
Thank you for developing these scripts; I'm excited to try Breath out as an alternative to crouton, which is now only supported in "maintenance mode." I read through the documentation and some of the open issues, and I had a couple of questions before I try this out on my Chromebook, as it's my main daily driver.

1. It seems as though the audio drivers come from the Sound Open Firmware (SOF) project. This means audio likely will not work on Chromebooks with Kabylake chipsets such as my ASUS C425 (LEONA), as SOF cannot get around a requirement for the firmware to be signed by Intel, evidenced by #30 and much weeping and gnashing of teeth in forums for those flashing UEFI firmware to install stock Linux distros. Are there any alternative ways to get sound working on these devices?
2. Can the Breath installation media be built on a microSD card instead of a USB flash drive? The ASUS C425 has only one USB type A slot which I need to use frequently in my workflow. I'd like to keep ChromeOS on my system for a while after trying Breath until I am confident it works for me, and the ability to stick a microSD card in (and forget about it!) to boot into Breath with `ctrl` `u`, or boot ChromeOS from the SSD via `ctrl` `d` would be extremely helpful. I read in one of the docs or the recent posts on Reddit that microSD cards work, but then I saw #32.
3. If I choose to install Debian, would that be Debian 11 "Bullseye"?

Thanks so much!

**Comment by MilkyDeveloper** [comment]
1. No. There really isn't anything I can do about it.
2. I've had reports of it working on some devices.
3. Yes

I'm currently looking at other porjects to develop. Sorry if I seem short and overly-apt with these responses!
