### ISSUE TITLE
After installing to internal storage, I am unable to create a swapfile.

### ISSUE THREAD

**Issue by jz5020** [MilkyDeveloper/cb-linux#45]
On my install of Ubuntu on my Chromebook reef, after running the `install-to-internal-storage` script, I have not been able to been able to add a swapfile following the ArchWiki instructions where I am met with `swapon: /swapfile: swapon failed: Invalid argument` after running the last command. I've searched on google where I have yet to have found a solution, so any help would really be appreciated.

**Comment by MilkyDeveloper** [comment]
Swap is not supported within the ChromeOS kernel. Try running `modprobe zram` for an alternative.
