### ISSUE TITLE
Is this project still being developed?

### ISSUE THREAD

**Issue by J0shuaT** [MilkyDeveloper/cb-linux#46]
Is this project still in development? There haven't been any updates in over a month. I am wondering if there is any hope I will get audio working on my Chromebook.

**Comment by MilkyDeveloper** [comment]
No, not at the moment. All other projects like this have more contributors. I'm sorry to say that I alone cannot add new features. I'll keep it working for currently supported devices though.

**Comment by J0shuaT** [comment]
I understand. I hope more people start contributing.
