### ISSUE TITLE
Setup script completes successfully but no user is created

### ISSUE THREAD

**Issue by jz5020** [MilkyDeveloper/cb-linux#5]
I ran the setup script from Ubuntu 20.04, where I had encounter 2 problems while trying to create my USB. The first was that since cgpt was automatically installed as a dependency, the script had failed the first time I tried running it but installing cgpt fixed the problem. The other major issue I had faced was that after the script had completed, seemingly without any major problems, I had found that no user had actually been created while running the setup script so afterwards, I had to manually chroot into the USB to add a user.

**Comment by MilkyDeveloper** [comment]
Both of these issues have been fixed in the latest commits.
