### ISSUE TITLE
Can't install to internal disk

### ISSUE THREAD

**Issue by jj1425** [MilkyDeveloper/cb-linux#7]
Hey there,

I got this installed to a USB drive and can boot into it fine, but when I installed it to my internal drive (using the install-to-internal-storage script) and tried to boot it by pressing CTRL-D I was presented with a screen that says "Chrome OS is missing or damaged, please remove all connected devices and start recovery". If I restart and boot back into the USB it works fine, I just can't seem to get it to boot from the internal drive.

Any suggestions? I'm on Navi (HP Chromebook x360)

**Comment by ArtemPozharov** [comment]
The same problem, bro! The script is not full-working!

**Comment by xaskibax** [comment]
@MilkyDeveloper I also have an issue with the latest install script, it seems **bzImage** is missing and it has a fatal error when repacking bzImage.signed, and then the system will not boot with CTRL-D or waiting.

**Comment by MilkyDeveloper** [comment]
I fixed it in the latest commit. Just run:
```
sudo wget https://raw.githubusercontent.com/MilkyDeveloper/cb-linux/main/bin/install-to-internal-storage -O /usr/local/bin/install-to-internal-storage
```
and then

```
sudo chmod +x /usr/local/bin/install-to-internal-storage
```
